name: MY-NEW-APP REACT APP CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-react:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy locally
        run: |
          rm -rf /var/www/my-new-app/*
          cp -r build/* /var/www/my-new-app/
