name: MY-NEW-APP REACT APP CI/CD

on:
  push:

jobs:
  deploy-react:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy locally
        run: |
          mkdir -p /home/host_user/apps_backup/my-new-app/
          cp -r dist/ /home/host_user/apps_backup/my-new-app/
